#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = iar.targets.arm.M4F{1,0,8.20,2
#
ble_release.xrm4f: package/cfg/ble_release.xrm4f.mak

clean::
	-$(RM) package/cfg/ble_release.xrm4f.mak
